apiVersion: addons.managed.openshift.io/v1alpha1
kind: Addon
metadata:
  name: reference-addon
spec:
  displayName: An amazing example addon!
  namespaces:
  - name: reference-addon
  install:
    type: OLMOwnNamespace
    olmOwnNamespace:
      namespace: reference-addon
      packageName: reference-addon
      channel: alpha
      catalogSourceImage: quay.io/osd-addons/reference-addon-index@sha256:58cb1c4478a150dc44e6c179d709726516d84db46e4e130a5227d8b76456b5bd
      additionalCatalogSources:
      - name: test-1
        image: quay.io/osd-addons/reference-addon-index@sha256:58cb1c4478a150dc44e6c179d709726516d84db46e4e130a5227d8b76456b5bd
  version: 1.0.0
  upgradePolicy:
    id: 123-456-789
  monitoring:
    federation:
      namespace: "reference-addon"
      matchNames:
      - reference_addon_foos_per_second
      portName: "portName"
      matchLabels:
        prometheus: reference-addon
